export const korisnici = [
    {
      id: 1,
      name: "Ana Anic",
      image: "/assets/store_photo/anica.jpg",
      email: "ana.anic@example.com",
      phoneNumber: "099-456-9999",
    },
    {
      id: 2,
      name: "Aleks Aleksic",
      image: "/assets/store_photo/max.jpg",
      email: "aleks.aleksic@example.com",
      phoneNumber: "095-446-7770",
    },
    {
      id: 3,
      name: "Marko Marković",
      image: "/assets/store_photo/marko.jpg",
      email: "marko.markovic@example.com",
      phoneNumber: "094-123-4567",
    },
    {
      id: 4,
      name: "Jovana Jovanović",
      image: "/assets/store_photo/jovana.jpg",
      email: "jovana.jovanovic@example.com",
      phoneNumber: "090-987-6543",
    },
    {
      id: 5,
      name: "Stefan Stefanović",
      image: "/assets/store_photo/stefan.jpg",
      email: "stefan.stefanovic@example.com",
      phoneNumber: "065-111-2222",
    },
    {
      id: 6,
      name: "Teodora Teodorović",
      image: "/assets/store_photo/teodora.jpg",
      email: "teodora.teodorovic@example.com",
      phoneNumber: "096-333-4444",
    },
    {
      id: 7,
      name: "Nikola Nikolić",
      image: "/assets/store_photo/nikola.jpg",
      email: "nikola.nikolic@example.com",
      phoneNumber: "093-555-6666",
    },
    {
      id: 8,
      name: "Milica Milenković",
      image: "/assets/store_photo/milica.jpg",
      email: "milica.milenkovic@example.com",
      phoneNumber: "062-777-8888",
    },
    {
      id: 9,
      name: "Luka Lukić",
      image: "/assets/store_photo/luka.jpg",
      email: "luka.lukic@example.com",
      phoneNumber: "091-999-0000",
    },
    {
      id: 10,
      name: "Tamara Tasić",
      image: "/assets/store_photo/tamara.jpg",
      email: "tamara.tasic@example.com",
      phoneNumber: "094-123-4567",
    },
  ];
  